version: '3.9'

services:
  frontend:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8081}
    image: frontend-despacho:latest
    container_name: frontend-despacho
    ports:
      - "80:80"
    restart: unless-stopped